version: '3.8'

services:
  app:
    container_name: app_kemal
    build: ./app
    ports:
      - 3000:3000
    environment:
      - APP_ENV=development
      - DATABASE_URI=postgres://postgres:1234@postgres_kemal:5432/crystal
    depends_on:
      - postgres
    volumes:
      - ./app/src:/app/src
      - ./app/db:/app/db

  postgres:
    container_name: postgres_kemal
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
